version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Fetching Docker Hub credentials from AWS Secrets Manager..."
      # Fetch Docker Hub credentials from Secrets Manager
      - export DOCKER_REGISTRY_USERNAME=$(aws secretsmanager get-secret-value --secret-id <add you secret manager arn>-us-JYDQoe --query SecretString --output text | jq -r '.username')
      - export DOCKER_REGISTRY_PASSWORD=$(aws secretsmanager get-secret-value --secret-id <add you secret manager arn>-us-JYDQoe --query SecretString --output text | jq -r '.password')
      - export DOCKER_REGISTRY_URL="https://index.docker.io/v1/"
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      # Log in to Docker Hub
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_USERNAME/hotel-app:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/hotel-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
